## AUTOGENERATED FILE.

# Compiler
CXX = g++

# Find all directories under 'src', 'include', and 'core'
INC_FLAGS := -Isrc/engine/include -Ithird_party -Ithird_party/GLAD -Ithird_party/GLFW -Ithird_party/GLM -Ithird_party/KHR -Ithird_party/stb

# 3. FLAGS
# -MMD -MP creates .d files to track header dependencies
CXXFLAGS  := -Wall -std=c++17 $(INC_FLAGS) -MMD -MP -fconcepts
LDFLAGS   := -Llib -lmingw32 -lglfw3 -lopengl32 -lgdi32

# Libraries
LDFLAGS = -Llib -lmingw32 -lglfw3 -lopengl32 -lgdi32

# Source files
SRC := $(shell find src -type f \( -name "*.cpp" -o -name "*.c" \))
SRC += $(shell find core -type f \( -name "*.cpp" -o -name "*.c" \))
OBJ := $(SRC:.cpp=.o)
OBJ := $(OBJ:.c=.o)

EXEC = game.exe

# Rules
all: $(EXEC)

$(EXEC): $(SRC)
	@mkdir -p $(dir $@)
	$(CXX) $(SRC) -o $@ $(CXXFLAGS) $(LDFLAGS)

clean:
	rm -rf build/*.exe

.PHONY: all clean