## AUTOGENERATED FILE.

# Compiler
CXX = g++

# Find all directories under 'src', 'include', and 'core'
INC_DIRS  := $(shell find src include core -type d 2> /dev/null)
INC_FLAGS := $(addprefix -I,$(INC_DIRS))

# 3. FLAGS
# -MMD -MP creates .d files to track header dependencies
CXXFLAGS  := -Wall -std=c++17 $(INC_FLAGS) -MMD -MP
LDFLAGS   := -Llib -lmingw32 -lglfw3 -lopengl32 -lgdi32

# Libraries
LDFLAGS = -Llib -lmingw32 -lglfw3 -lopengl32 -lgdi32

# Source files
SRC := $(shell find src Core -type f \( -name "*.cpp" -o -name "*.c" \))
OBJ := $(SRC:.cpp=.o)
OBJ := $(OBJ:.c=.o)

EXEC = game.exe

# Rules
all: $(EXEC)

$(EXEC): $(SRC)
	@mkdir -p $(dir $@)
	$(CXX) $(SRC) -o $@ $(CXXFLAGS) $(LDFLAGS)

clean:
	rm -rf build/*.exe

.PHONY: all clean