## AUTOGENERATED FILE.

# Compiler
CXX = g++
CXXFLAGS = -Wall -std=c++17 -Icore -Iinclude -Iinclude/Vendors

# Libraries
LDFLAGS = -Llib -lmingw32 -lglfw3 -lopengl32 -lgdi32

# Source files
SRC = src/main.cpp $(wildcard src/**/*.cpp src/**/*.c) $(wildcard core/*.cpp core/*.c) $(wildcard core/**/*.cpp core/**/*.c)
# Output
EXEC = build/game.exe

# Rules
all: $(EXEC)

$(EXEC): $(SRC)
	@mkdir -p $(dir $@)
	$(CXX) $(SRC) -o $@ $(CXXFLAGS) $(LDFLAGS)

clean:
	rm -rf build/*.exe

.PHONY: all clean